# -*- coding: utf-8 -*-
"""explaination.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXpNedYgSiN0GJFml19NMW7BBTfyvaZD
"""

import anthropic
import base64
import json
import os
from typing import Any

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

SYSTEM_PROMPT = """You are a medical prescription parser with expertise in Indian prescriptions.
Extract structured data from prescription images accurately.
Always return valid JSON only — no markdown, no explanation, no preamble.
If a brand name looks like an Indian drug (e.g. Crocin, Augmentin, Glycomet, Pantop, Dolo),
make your best guess at the generic/active ingredient and set confidence to medium.
"""

USER_PROMPT = """Extract all medicines from this prescription image and return a JSON object.

For each medicine extract:
- brand_name: the name written on the prescription (as-is)
- generic_name: the active ingredient if identifiable, else null
- dose: dosage amount (e.g. "500mg", "10ml"), null if not found
- frequency: how often (e.g. "twice daily", "OD", "BD", "TDS"), null if not found
- duration: how long (e.g. "5 days", "1 month"), null if not found
- route: how taken (e.g. "oral", "topical", "injection"), null if not found
- instructions: special notes (e.g. "after food", "at bedtime"), null if not found

Also extract:
- raw_text: the full readable text visible in the image as a single string
- doctor_name: the prescribing doctor's name if visible, else null
- date: prescription date if visible, else null
- confidence: "high" if clearly readable, "medium" if partially unclear, "low" if mostly unreadable

Return ONLY this JSON structure:
{
  "medicines": [
    {
      "brand_name": "...",
      "generic_name": "...",
      "dose": "...",
      "frequency": "...",
      "duration": "...",
      "route": "...",
      "instructions": "..."
    }
  ],
  "raw_text": "...",
  "doctor_name": "...",
  "date": "...",
  "confidence": "high|medium|low"
}

If the image is not a prescription or is completely unreadable, return:
{ "error": "brief reason why it cannot be parsed" }
"""


def _get_media_type(content_type: str) -> str:
    """Map content type to Anthropic-accepted media type."""
    mapping = {
        "image/jpeg": "image/jpeg",
        "image/png": "image/png",
        "image/webp": "image/webp",
        "image/gif": "image/gif",
    }
    return mapping.get(content_type, "image/jpeg")


async def extract_prescription(image_bytes: bytes, content_type: str) -> dict[str, Any]:
    """
    Send prescription image to Claude Vision and return structured extracted data.

    Args:
        image_bytes: raw image bytes
        content_type: MIME type of the image

    Returns:
        dict with medicines list and metadata, or {"error": "reason"} on failure
    """
    if not ANTHROPIC_API_KEY:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set.")

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    # Handle PDF — convert first page to image (requires pdf2image in production)
    if content_type == "application/pdf":
        # For hackathon: ask user to upload image instead
        # Production: use pdf2image to convert page 1
        return {"error": "PDF support coming soon. Please upload a JPG or PNG photo of the prescription."}

    image_b64 = base64.standard_b64encode(image_bytes).decode("utf-8")
    media_type = _get_media_type(content_type)

    message = client.messages.create(
        model="claude-3-opus-20240229",
        max_tokens=1500,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": image_b64,
                        },
                    },
                    {
                        "type": "text",
                        "text": USER_PROMPT
                    }
                ],
            }
        ],
    )

    raw_response = message.content[0].text.strip()

    # Strip accidental markdown fences
    if raw_response.startswith("```"):
        raw_response = raw_response.split("```")[1]
        if raw_response.startswith("json"):
            raw_response = raw_response[4:]
        raw_response = raw_response.strip()

    try:
        result = json.loads(raw_response)
    except json.JSONDecodeError:
        # Try to extract JSON from the response
        import re
        json_match = re.search(r'\{.*\}', raw_response, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group())
        else:
            return {"error": "Could not parse prescription. Please try a clearer image."}

    return result

import anthropic
import json
import os
from typing import Any

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

SYSTEM_PROMPT = """You are a friendly medical assistant helping patients in India understand their prescriptions.
Explain medicines in simple, clear English that a non-medical person can understand.
Be reassuring, accurate, and practical. Focus on what the patient actually needs to know.
Always return valid JSON only — no markdown, no explanation, no preamble.
"""

def _build_user_prompt(medicines: list[dict]) -> str:
    return f"""Explain each medicine below for a patient in India. Use simple, friendly language.

Medicines:
{json.dumps(medicines, indent=2)}

For each medicine return:
- brand_name: same as input (required — used for matching)
- what_it_is: one clear sentence explaining what this medicine does (e.g. "A painkiller that reduces fever and relieves mild pain and headaches")
- how_to_take: plain English instruction combining dose + frequency + instructions (e.g. "Take 1 tablet by mouth twice a day, after meals, for 5 days")
- common_side_effects: array of exactly 2–3 most common side effects in plain language (e.g. ["Mild nausea", "Dizziness", "Dry mouth"])
- important_warning: the single most critical thing to know or avoid, null if nothing critical
- safe_with_food: true if should be taken with food, false if on empty stomach, null if doesn't matter

Return ONLY a JSON array:
[
  {{
    "brand_name": "...",
    "what_it_is": "...",
    "how_to_take": "...",
    "common_side_effects": ["...", "...", "..."],
    "important_warning": "...",
    "safe_with_food": true
  }}
]"""


async def explain_medicines(medicines: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Generate plain-language explanations for a list of extracted medicines.

    Args:
        medicines: list of medicine dicts from OCR extraction

    Returns:
        list of explanation dicts, one per medicine
    """
    if not ANTHROPIC_API_KEY:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set.")

    if not medicines:
        return []

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    # Trim to relevant fields only to save tokens
    slim_meds = [
        {
            "brand_name": m.get("brand_name", ""),
            "generic_name": m.get("generic_name"),
            "dose": m.get("dose"),
            "frequency": m.get("frequency"),
            "duration": m.get("duration"),
            "route": m.get("route"),
            "instructions": m.get("instructions"),
        }
        for m in medicines
    ]

    message = client.messages.create(
        model="claude-3-opus-20240229",
        max_tokens=1500,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": _build_user_prompt(slim_meds)
            }
        ],
    )

    raw_response = message.content[0].text.strip()

    # Strip markdown fences
    if raw_response.startswith("```"):
        raw_response = raw_response.split("```")[1]
        if raw_response.startswith("json"):
            raw_response = raw_response[4:]
        raw_response = raw_response.strip()

    try:
        explanations = json.loads(raw_response)
        if isinstance(explanations, list):
            return explanations
        # Sometimes Claude returns {"explanations": [...]}
        if isinstance(explanations, dict) and "explanations" in explanations:
            return explanations["explanations"]
    except json.JSONDecodeError:
        pass

    # Graceful fallback — return basic info without explanations
    return [
        {
            "brand_name": m.get("brand_name", ""),
            "what_it_is": None,
            "how_to_take": f"{m.get('dose', '')} {m.get('frequency', '')}".strip() or None,
            "common_side_effects": [],
            "important_warning": None,
            "safe_with_food": None
        }
        for m in medicines
    ]