# -*- coding: utf-8 -*-
"""interactions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyqN47F3DQlAMp_p6mcp5PeDVe_yR1qb
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile interactions.py
# """
# interactions.py — Drug interaction checker via RxNorm (NLM) free API
# No API key required. Uses generic/active ingredient names.
# 
# RxNorm docs: https://rxnav.nlm.nih.gov/InteractionAPIs.html
# """
# 
# import httpx
# import asyncio
# from typing import Any
# 
# RXNORM_BASE = "https://rxnav.nlm.nih.gov/REST"
# 
# # Timeout config
# TIMEOUT = httpx.Timeout(10.0, connect=5.0)
# 
# # Common Indian brand name → generic name overrides
# # Extend this list over time as you encounter more Indian brands
# INDIA_BRAND_OVERRIDES: dict[str, str] = {
#     "crocin": "paracetamol",
#     "dolo": "paracetamol",
#     "calpol": "paracetamol",
#     "combiflam": "ibuprofen paracetamol",
#     "brufen": "ibuprofen",
#     "zerodol": "aceclofenac",
#     "voveran": "diclofenac",
#     "pan": "pantoprazole",
#     "pantop": "pantoprazole",
#     "omez": "omeprazole",
#     "rantac": "ranitidine",
#     "augmentin": "amoxicillin clavulanate",
#     "mox": "amoxicillin",
#     "cifran": "ciprofloxacin",
#     "glycomet": "metformin",
#     "glucophage": "metformin",
#     "ecosprin": "aspirin",
#     "stamlo": "amlodipine",
#     "telma": "telmisartan",
#     "amlip": "amlodipine",
#     "atorva": "atorvastatin",
#     "rozavel": "rosuvastatin",
#     "clavix": "clopidogrel",
#     "deplatt": "clopidogrel",
#     "stugeron": "cinnarizine",
#     "vertin": "betahistine",
#     "allegra": "fexofenadine",
#     "cetirizine": "cetirizine",
#     "montair": "montelukast",
#     "asthalin": "salbutamol",
#     "deriphyllin": "theophylline etofylline",
#     "amoxil": "amoxicillin",
#     "azithral": "azithromycin",
#     "zithromax": "azithromycin",
# }
# 
# 
# def _resolve_generic(medicine: dict[str, Any]) -> str | None:
#     """
#     Resolve a medicine to its generic/active ingredient name for RxNorm lookup.
#     Tries: generic_name field → brand name override map → brand name itself.
#     """
#     # Use generic_name if provided and not null
#     generic = medicine.get("generic_name")
#     if generic and generic.strip():
#         return generic.strip().lower()
# 
#     # Try brand name in override map
#     brand = medicine.get("brand_name", "").lower().strip()
#     # Strip common suffixes (dosage, form) e.g. "Crocin 500" → "crocin"
#     brand_base = brand.split()[0] if brand else ""
#     if brand_base in INDIA_BRAND_OVERRIDES:
#         return INDIA_BRAND_OVERRIDES[brand_base]
# 
#     # Fall back to brand name itself (often works for global brands)
#     return brand if brand else None
# 
# 
# async def _get_rxcui(client: httpx.AsyncClient, drug_name: str) -> str | None:
#     """Resolve a drug name to its RxCUI identifier."""
#     try:
#         resp = await client.get(
#             f"{RXNORM_BASE}/rxcui.json",
#             params={"name": drug_name, "search": "1"},
#             timeout=TIMEOUT
#         )
#         data = resp.json()
#         rxcui = data.get("idGroup", {}).get("rxnormId", [None])[0]
#         return rxcui
#     except Exception:
#         return None
# 
# 
# async def _check_pair(client: httpx.AsyncClient, rxcui1: str, rxcui2: str) -> list[dict]:
#     """Check interactions between two RxCUI identifiers."""
#     try:
#         resp = await client.get(
#             f"{RXNORM_BASE}/interaction/list.json",
#             params={"rxcuis": f"{rxcui1} {rxcui2}"},
#             timeout=TIMEOUT
#         )
#         data = resp.json()
#         pairs = (
#             data.get("fullInteractionTypeGroup", [{}])[0]
#             .get("fullInteractionType", [{}])[0]
#             .get("interactionPair", [])
#         )
#         return pairs
#     except Exception:
#         return []
# 
# 
# async def check_interactions(medicines: list[dict[str, Any]]) -> dict[str, Any]:
#     """
#     Check drug interactions for all pairs of medicines using RxNorm free API.
# 
#     Args:
#         medicines: list of medicine dicts with brand_name and optional generic_name
# 
#     Returns:
#         dict with has_interactions, interaction_pairs, drugs_checked, drugs_skipped
#     """
#     if len(medicines) < 2:
#         return {
#             "has_interactions": False,
#             "interaction_pairs": [],
#             "drugs_checked": [],
#             "drugs_skipped": []
#         }
# 
#     async with httpx.AsyncClient() as client:
#         # Resolve generics and get RxCUIs concurrently
#         resolved = []  # (brand_name, generic_name, rxcui)
#         skipped = []
# 
#         resolve_tasks = []
#         for med in medicines:
#             generic = _resolve_generic(med)
#             if generic:
#                 resolve_tasks.append((med["brand_name"], generic, _get_rxcui(client, generic)))
#             else:
#                 skipped.append(med.get("brand_name", "unknown"))
# 
#         # Await all rxcui lookups
#         for brand_name, generic, coro in resolve_tasks:
#             rxcui = await coro
#             if rxcui:
#                 resolved.append((brand_name, generic, rxcui))
#             else:
#                 skipped.append(brand_name)
# 
#         drugs_checked = [r[0] for r in resolved]
# 
#         # Check all pairs
#         interaction_pairs = []
#         for i in range(len(resolved)):
#             for j in range(i + 1, len(resolved)):
#                 brand1, generic1, rxcui1 = resolved[i]
#                 brand2, generic2, rxcui2 = resolved[j]
# 
#                 pairs = await _check_pair(client, rxcui1, rxcui2)
#                 for pair in pairs:
#                     description = pair.get("description", "")
#                     severity = pair.get("severity", None)
#                     if description:
#                         interaction_pairs.append({
#                             "drug_1": brand1,
#                             "drug_2": brand2,
#                             "severity": severity,
#                             "description": description,
#                             "source": "rxnorm"
#                         })
# 
#     return {
#         "has_interactions": len(interaction_pairs) > 0,
#         "interaction_pairs": interaction_pairs,
#         "drugs_checked": drugs_checked,
#         "drugs_skipped": skipped
#     }