# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXpNedYgSiN0GJFml19NMW7BBTfyvaZD
"""

import sys
!{sys.executable} -m pip install fastapi uvicorn python-multipart httpx pillow anthropic

"""
RxDigitizer Backend — Prescription OCR + Drug Conflict Checker
FastAPI backend for hackathon-ready prescription digitizer

Run:
    uvicorn main:app --reload --port 8000

API Docs: http://localhost:8000/docs
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import base64
import httpx
import anthropic
import json
import asyncio
from typing import Optional
from models import (
    PrescriptionResponse, ExplainRequest, ExplainResponse,
    InteractionResponse, FullAnalysisResponse
)
from ocr import extract_prescription
from explaination import explain_medicines
from interactions import check_interactions

app = FastAPI(
    title="RxDigitizer API",
    description="Prescription OCR, plain-language explanation, and drug interaction checker",
    version="1.0.0"
)

# Allow all origins for hackathon — tighten in production
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    return {"status": "ok", "message": "RxDigitizer API is running"}


@app.post("/analyze", response_model=FullAnalysisResponse, summary="Full pipeline: OCR + explain + interactions")
async def analyze_prescription(file: UploadFile = File(...)):
    """
    Main endpoint. Upload a prescription image (JPG/PNG/PDF).
    Returns: extracted medicines + plain-language explanations + interaction flags.
    All three steps run, with interactions checked in parallel to explanations.
    """
    # Validate file type
    allowed_types = {"image/jpeg", "image/png", "image/webp", "application/pdf"}
    if file.content_type not in allowed_types:
        raise HTTPException(status_code=400, detail=f"Unsupported file type: {file.content_type}. Use JPG, PNG, WEBP, or PDF.")

    image_bytes = await file.read()
    if len(image_bytes) > 10 * 1024 * 1024:  # 10MB limit
        raise HTTPException(status_code=400, detail="File too large. Max 10MB.")

    # Step 1: OCR + extraction
    extracted = await extract_prescription(image_bytes, file.content_type)
    if "error" in extracted:
        raise HTTPException(status_code=422, detail=extracted["error"])

    medicines = extracted.get("medicines", [])
    if not medicines:
        raise HTTPException(status_code=422, detail="No medicines found in this image. Please upload a clearer prescription photo.")

    # Steps 2 & 3: run explain + interactions in parallel
    explain_task = explain_medicines(medicines)
    interaction_task = check_interactions(medicines)
    explanations, interactions = await asyncio.gather(explain_task, interaction_task)

    # Merge explanation data into each medicine
    explain_map = {e["brand_name"]: e for e in explanations}
    enriched = []
    for med in medicines:
        info = explain_map.get(med["brand_name"], {})
        enriched.append({**med, **info})

    return FullAnalysisResponse(
        medicines=enriched,
        interactions=interactions,
        doctor_name=extracted.get("doctor_name"),
        date=extracted.get("date"),
        confidence=extracted.get("confidence", "medium"),
        raw_text=extracted.get("raw_text")
    )


@app.post("/ocr", response_model=PrescriptionResponse, summary="OCR only — extract raw structured data")
async def ocr_only(file: UploadFile = File(...)):
    """Extract medicines from image without explanation or interaction check."""
    image_bytes = await file.read()
    extracted = await extract_prescription(image_bytes, file.content_type)
    if "error" in extracted:
        raise HTTPException(status_code=422, detail=extracted["error"])
    return PrescriptionResponse(**extracted)


@app.post("/explain", response_model=ExplainResponse, summary="Explain a list of medicines in plain language")
async def explain_only(payload: ExplainRequest):
    """
    Takes a list of medicine objects (from /ocr output) and returns
    plain-language explanations for each.
    """
    explanations = await explain_medicines(payload.medicines)
    return ExplainResponse(explanations=explanations)


@app.post("/interactions", response_model=InteractionResponse, summary="Check drug interactions")
async def interactions_only(payload: ExplainRequest):
    """
    Check interactions for a list of medicines via RxNorm.
    Uses generic_name field for lookup — brand names that don't resolve are skipped.
    """
    result = await check_interactions(payload.medicines)
    return InteractionResponse(**result)


@app.get("/health")
async def health():
    return {"status": "healthy"}