# -*- coding: utf-8 -*-
"""models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxs7aKtytcF41L7SSUiP7ONH9g6VaRZV
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile models.py
# """
# Pydantic models for RxDigitizer API
# """
# 
# from pydantic import BaseModel
# from typing import Optional, List, Any
# 
# 
# class Medicine(BaseModel):
#     brand_name: str
#     generic_name: Optional[str] = None
#     dose: Optional[str] = None
#     frequency: Optional[str] = None
#     duration: Optional[str] = None
#     route: Optional[str] = None
#     instructions: Optional[str] = None
# 
# 
# class MedicineEnriched(BaseModel):
#     brand_name: str
#     generic_name: Optional[str] = None
#     dose: Optional[str] = None
#     frequency: Optional[str] = None
#     duration: Optional[str] = None
#     route: Optional[str] = None
#     instructions: Optional[str] = None
#     # Explanation fields
#     what_it_is: Optional[str] = None
#     how_to_take: Optional[str] = None
#     common_side_effects: Optional[List[str]] = None
#     important_warning: Optional[str] = None
#     safe_with_food: Optional[bool] = None
# 
# 
# class PrescriptionResponse(BaseModel):
#     medicines: List[Medicine]
#     doctor_name: Optional[str] = None
#     date: Optional[str] = None
#     confidence: str = "medium"
#     raw_text: Optional[str] = None
# 
# 
# class ExplainRequest(BaseModel):
#     medicines: List[Medicine]
# 
# 
# class ExplanationItem(BaseModel):
#     brand_name: str
#     what_it_is: Optional[str] = None
#     how_to_take: Optional[str] = None
#     common_side_effects: Optional[List[str]] = None
#     important_warning: Optional[str] = None
#     safe_with_food: Optional[bool] = None
# 
# 
# class ExplainResponse(BaseModel):
#     explanations: List[ExplanationItem]
# 
# 
# class InteractionPair(BaseModel):
#     drug_1: str
#     drug_2: str
#     severity: Optional[str] = None
#     description: str
#     source: str = "rxnorm"
# 
# 
# class InteractionResponse(BaseModel):
#     has_interactions: bool
#     interaction_pairs: List[InteractionPair] = []
#     drugs_checked: List[str] = []
#     drugs_skipped: List[str] = []
# 
# 
# class FullAnalysisResponse(BaseModel):
#     medicines: List[MedicineEnriched]
#     interactions: InteractionResponse
#     doctor_name: Optional[str] = None
#     date: Optional[str] = None
#     confidence: str
#     raw_text: Optional[str] = None